name: Publication du site ...

on:
  push:
    branches:
      - main

jobs:

  # - checkout master ou main
  # - build des binaires
  # - build package des sources
  # - build jsdoc
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build bundle
        run: npm run build:bundle

      - name: Build modules
        run: npm run build:modules

      - name: Build package
        run: npm run publish
  
      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: Upload JSDoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jsdoc
          path: jsdoc
  
  # - checkout gh-pages
  # - download des artifacts : build & jsdoc
  # - commit & push
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: IGNF/geoportal-extensions-openlayers
          ref: gh-pages
      
      - name: Download Binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: Download JSDoc artifacts
        uses: actions/download-artifact@v4
        with:
          name: jsdoc
          path: jsdoc
      
      - name: Build 404
        run: |
          cp index.html 404.html
  
      - name: Publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "build project gh-pages"
          git push

