name: Publication du site ...

on:
  push:
    branches:
      - main

jobs:

  # - checkout master ou main
  # - build des binaires
  # - build package des sources
  # - build jsdoc
  build-linux:
    if: ${{ !contains(github.event.head_commit.message, '[github-actions]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build bundle
        run: npm run build:bundle

      - name: Build modules
        run: npm run build:modules

      - name: Build package
        run: npm run publish
      
      - name: Build jsdoc
        run: npm run generate-tsdoc
  
      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: Upload JSDoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jsdoc
          path: jsdoc
  
  build-windows:
    if: ${{ !contains(github.event.head_commit.message, '[github-actions]') }}
    # This job is optional and will run only if the previous job fails
    # It is useful to ensure that the build can also run on Windows
    # and to provide a Windows binary if needed.
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'

      - name: Install dependencies
        run: npm install
      
      - name: Fix line endings
        run: npm run lintfix

      - name: Build bundle
        run: npm run build:bundle

      - name: Build modules
        run: npm run build:modules

      - name: Build package
        run: npm run publish
        
  # - checkout gh-pages
  # - download des artifacts : build & jsdoc
  # - commit & push
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[github-actions]') }}
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: IGNF/geopf-extensions-openlayers
          ref: gh-pages
      
      - name: Download Binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: Download JSDoc artifacts
        uses: actions/download-artifact@v4
        with:
          name: jsdoc
          path: jsdoc
      
      - name: Build 404
        run: |
          cp index.html 404.html
  
      - name: Publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "build project gh-pages"
          git push

